/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#bec6e0",
        "surface-tint": "#565e74",
        "surface-container": "#f0edef",
        "on-tertiary-fixed": "#191c1e",
        "on-secondary-fixed": "#0d1c2f",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-container-low": "#f6f3f5",
        "secondary-fixed": "#d5e3fd",
        "inverse-surface": "#303032",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "background": "#fcf8fa",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485c",
        "surface-container-high": "#eae7e9",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "surface-variant": "#e4e2e4",
        "error": "#ba1a1a",
        "on-secondary-container": "#57657b",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#444749",
        "tertiary": "#000000",
        "surface-bright": "#fcf8fa",
        "surface": "#fcf8fa",
        "primary": "#000000",
        "tertiary-container": "#191c1e",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "surface-container-highest": "#e4e2e4",
        "on-background": "#1b1b1d",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#f3f0f2",
        "on-surface": "#1b1b1d",
        "on-primary-container": "#7c839b",
        "secondary": "#515f74",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-dim": "#dcd9db",
        "on-tertiary-container": "#818486",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d5e3fd",
        "on-surface-variant": "#45464d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "8px",
        "md": "16px",
        "touch-target": "44px",
        "edge-margin": "16px",
        "xl": "32px",
        "sm": "12px",
        "lg": "24px",
        "base": "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
}
