/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated.upload'
import { Route as AuthenticatedSkillGapRouteImport } from './routes/_authenticated.skill-gap'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedAssociatesRouteImport } from './routes/_authenticated.associates'
import { Route as AuthenticatedAllocationRouteImport } from './routes/_authenticated.allocation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAssociatesIdRouteImport } from './routes/_authenticated.associates.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSkillGapRoute = AuthenticatedSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssociatesRoute = AuthenticatedAssociatesRouteImport.update({
  id: '/associates',
  path: '/associates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAllocationRoute = AuthenticatedAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssociatesIdRoute =
  AuthenticatedAssociatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssociatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/allocation': typeof AuthenticatedAllocationRoute
  '/associates': typeof AuthenticatedAssociatesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/associates/$id': typeof AuthenticatedAssociatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/allocation': typeof AuthenticatedAllocationRoute
  '/associates': typeof AuthenticatedAssociatesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/associates/$id': typeof AuthenticatedAssociatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/allocation': typeof AuthenticatedAllocationRoute
  '/_authenticated/associates': typeof AuthenticatedAssociatesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/skill-gap': typeof AuthenticatedSkillGapRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/associates/$id': typeof AuthenticatedAssociatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/allocation'
    | '/associates'
    | '/reports'
    | '/skill-gap'
    | '/upload'
    | '/associates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/allocation'
    | '/associates'
    | '/reports'
    | '/skill-gap'
    | '/upload'
    | '/associates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/allocation'
    | '/_authenticated/associates'
    | '/_authenticated/reports'
    | '/_authenticated/skill-gap'
    | '/_authenticated/upload'
    | '/_authenticated/associates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/skill-gap': {
      id: '/_authenticated/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof AuthenticatedSkillGapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/associates': {
      id: '/_authenticated/associates'
      path: '/associates'
      fullPath: '/associates'
      preLoaderRoute: typeof AuthenticatedAssociatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/allocation': {
      id: '/_authenticated/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AuthenticatedAllocationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/associates/$id': {
      id: '/_authenticated/associates/$id'
      path: '/$id'
      fullPath: '/associates/$id'
      preLoaderRoute: typeof AuthenticatedAssociatesIdRouteImport
      parentRoute: typeof AuthenticatedAssociatesRoute
    }
  }
}

interface AuthenticatedAssociatesRouteChildren {
  AuthenticatedAssociatesIdRoute: typeof AuthenticatedAssociatesIdRoute
}

const AuthenticatedAssociatesRouteChildren: AuthenticatedAssociatesRouteChildren =
  {
    AuthenticatedAssociatesIdRoute: AuthenticatedAssociatesIdRoute,
  }

const AuthenticatedAssociatesRouteWithChildren =
  AuthenticatedAssociatesRoute._addFileChildren(
    AuthenticatedAssociatesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAllocationRoute: typeof AuthenticatedAllocationRoute
  AuthenticatedAssociatesRoute: typeof AuthenticatedAssociatesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSkillGapRoute: typeof AuthenticatedSkillGapRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAllocationRoute: AuthenticatedAllocationRoute,
  AuthenticatedAssociatesRoute: AuthenticatedAssociatesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSkillGapRoute: AuthenticatedSkillGapRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
